"""
pipeline.py

High-level pipeline functions for executing the xSAR scoring and annotation process.
These functions orchestrate the bit processing, scoring, and annotation steps for both
labeled and unlabeled compound sets.

Dependencies:
    - pandas
    - scripts.fingerprints
    - scripts.bit_processing
    - scripts.scoring
    - scripts.annotation
"""

import pandas as pd

from scripts.fingerprints import process_dataframe_bits
from scripts.bit_processing import (
    get_unsampled_bits,
    get_conserved_binding_bits,
    get_conserved_non_binding_bits,
    get_unconservative_bits
)
from scripts.scoring import (
    get_bit_conservation_scores_from_binders,
    get_postive_binding_scores,
    get_negative_binding_scores,
    predict_PBS_binders,
    predict_NBS_nonbinders
)
from scripts.annotation import (
    annotate_bits,
    annotate_PBS_binders,
    annotate_NBS_nonbinders,
)


def analyse_score(
    df: pd.DataFrame,
    precomputed: bool = False,
    radius: int = 6,
    nBits: int = 2048,
    useFeatures: bool = True,
) -> pd.DataFrame:
    """
    Main pipeline to compute conservation-based SAR scores and annotate compounds.

    Args:
        TODO: define df column and dataformat
        df (pd.DataFrame): Input dataframe with 'Smiles' and 'Binding' columns.
        precomputed (bool): Whether fingerprint bits are already processed.
            This allows to feed a dataframe with different input descriptors to the scoring pipeline provided
            the input dataframe has the same format as the one generated by this pipeline
        radius, nBits, useFeatures: Fingerprint generation parameters.
        nBits (int): Length of fingerprint.
        useFeatures (bool): Whether to use atom features in fingerprinting.

    Returns:
        pd.DataFrame: Fully annotated dataframe including PBS/NBS scores and predictions.
    """
    if not precomputed:
        df_bits = process_dataframe_bits(df, radius=radius, nBits=nBits, useFeatures=useFeatures)
    else:
        # Only keep compound rows
        compound_rows = df.index.get_level_values(0) == 'Compound'
        df_bits = df.loc[compound_rows]

        # Keep only relevant columns
        allowed_namespaces = ['Reference', 'Fingerprint']
        df_bits = df_bits.loc[:, df_bits.columns.get_level_values(0).isin(allowed_namespaces)]

        # Coerce 'Binding' to bool if present
        if ('Reference', 'Binding') in df_bits.columns:
            df_bits[('Reference', 'Binding')] = df_bits[('Reference', 'Binding')].astype(bool)

    # Bit-level analysis
    conservation_scores = get_bit_conservation_scores_from_binders(df_bits)
    CBB = get_conserved_binding_bits(conservation_scores)
    unsampled = get_unsampled_bits(df_bits)
    CNB = get_conserved_non_binding_bits(conservation_scores, unsampled)
    unconserved = get_unconservative_bits(conservation_scores)

    df_annotated = annotate_bits(df_bits, conservation_scores, CBB, CNB, unconserved, unsampled)

    # Compound-level PBS/NBS scoring
    PBS_scores = get_postive_binding_scores(df_bits, CBB)
    PBS_binder = predict_PBS_binders(df_bits, CBB)
    df_annotated = annotate_PBS_binders(df_annotated, PBS_scores, PBS_binder)

    NBS_scores = get_negative_binding_scores(df_bits, CNB)
    NBS_nonbinder = predict_NBS_nonbinders(df_bits, CNB)
    df_annotated = annotate_NBS_nonbinders(df_annotated, NBS_scores, NBS_nonbinder)

    return df_annotated


def score_unmeasured_compounds(
        df_reference: pd.DataFrame,
        df_to_score: pd.DataFrame,
        precomputed: bool = False,
        radius: int = 6,
        nBits: int = 2048,
        useFeatures: bool = True,
) -> pd.DataFrame:
    """
    Score new compounds using binding information learned from a labeled reference set.

    Args:
        df_reference (pd.DataFrame): Labeled dataframe used to learn conservation profiles.
            Must include at least Name, Smiles, and Binding columns.
        df_to_score (pd.DataFrame): Unlabeled dataframe to score. Must include Name and Smiles columns.
        precomputed (bool): If True, assumes df_reference and df_to_score are already bit-encoded
            with correct MultiIndex.
        radius (int): Radius of ECFP fingerprint.
        nBits (int): Length of fingerprint.
        useFeatures (bool): Whether to use atom features in fingerprinting.

    Returns:
        pd.DataFrame: Scored dataframe with MultiIndex. Includes PBS/NBS scores and binary predictions.
    """
    df_ref = analyse_score(
        df_reference,
        precomputed=precomputed,
        radius=radius,
        nBits=nBits,
        useFeatures=useFeatures,
    )

    bit_labels = df_ref.loc[('Bits', 'Conservation label'), 'Fingerprint']
    binding_indices = [bit for bit, label in bit_labels.items() if label == 'Binding']
    nonbinding_indices = [bit for bit, label in bit_labels.items() if label == 'Non-binding']

    df_to_score_bits = (
        df_to_score.copy() if precomputed
        else process_dataframe_bits(df_to_score, radius=radius, nBits=nBits, useFeatures=useFeatures)
    )

    # Compute scores
    PBS_scores = get_postive_binding_scores(df_to_score_bits, binding_indices)
    NBS_scores = get_negative_binding_scores(df_to_score_bits, nonbinding_indices)

    # Predict
    PBS_predicted = predict_PBS_binders(df_to_score_bits, binding_indices)
    NBS_predicted = predict_NBS_nonbinders(df_to_score_bits, nonbinding_indices)

    df_annotated = annotate_PBS_binders(df_to_score_bits, PBS_scores, PBS_predicted)
    df_annotated = annotate_NBS_nonbinders(df_annotated, NBS_scores, NBS_predicted)

    return df_annotated